baseURL = 'http://mmcelreath.github.io/'
languageCode = 'en-us'
title = 'Automation Creations'
theme = 'Hugo-Octopress'


# Disqus shortcode
# Disable comments for any individual post by adding "comments: false" in its frontmatter
# disqusShortname = "Your disqus shortname"

# Number of blog posts in each pagination page
paginate = 6

[permalinks]
# Configures post URLs
post = "/blog/:year-:month-:day-:title/"

[params]

  # If false, all contents of posts will appear on the front page and in pagination
  truncate = true

  # Author's name (appears in meta tags and under posts)
  author = "Automation Creations"

  # This text appears in site header under website title
#   subtitle = "Subtitle appears under website title"

  # Search engine URL
  searchEngineURL = "https://www.google.com/search"

  # Text of the "Continue Reading" label. Supports markdown and inline HTML.
  # For example, &rarr; == right arrow.
  continueReadingText = "Would you like to know more? &rarr;"

  # Google analytics code - remove if you do not have/want Google Analytics - needs JavaScript
#   googleAnalytics = "UA-XXXXX-X"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"

  # Switch to true to enable RSS icon link
  rss = true

  # Set to true to use a text label for RSS instead of an icon
  # This is overwritten by the "rss" setting
  textrss = false

  # Website's default description
  description = "Test"

  # Populate with your search keywords - these will appear in meta tags
  defaultKeywords = ["automation" , "powershell" , "azure" , "terraform", "cloud", "tutorial", "web apps", "app service"]

  # Set to true to hide ReadingTime on posts
  disableReadingTime = false

  # Set to true to disable downloading of remote Google fonts
  disableGoogleFonts = false

  # Remove or set to false to use local fonts
  remoteFonts = false

  # Remove or set to false to use FontAwesome CDN, otherwise, the theme uses ForkAwesome local fonts.
  # fontAwesome = false
  
  # If set to true, navigation menu links will open in a new window with the exception of links to root ("/")
  # If this item does not exist or is set to false, then navigation menu links will open in the same window
  navigationNewWindow = true

  github = "https://github.com/mmcelreath"
  twitter = "https://twitter.com/Mmcelreath"
  linkedin = "https://www.linkedin.com/in/matt-mcelreath-ma/"
  youtube = "https://www.youtube.com/channel/UCBmvsfL6OKpUBfLArIskOcA"

[[menu.main]]
  Name = "Home"
  URL = "/"
  weight = -10

[[menu.main]]
  Name = "YouTube Channel"
  URL = "https://www.youtube.com/channel/UCBmvsfL6OKpUBfLArIskOcA"
  weight = -5

[[menu.main]]
  Name = "TechSnips"
  URL = "https://techsnips.io/contributors/matt-mcelreath/"

sidebarHeader = "Sidebar Header"

sidebarText = "Here's a [link to google](https://www.google.com)"